### ISSUE TITLE
ui-tree demo wont work correctly when docked in main app window panels

### ISSUE THREAD

**Issue by nibzo1** [fireball-packages/ui-tree#2]
Hi,

Im working with Editor-framework and have installed a few of the excellent demo packages. 

There appears to be an issue with ui-tree not working when it is docked in a panel in the main app window

Observe the image below. The tree is successful rendered although there is no collapsible sections
![image](https://cloud.githubusercontent.com/assets/2906176/17108708/9650c546-528c-11e6-86b5-f20c2aed6452.png)

If i pop the tab out to a new independent panel it works as expected. There are no errors in the console, dev-tools console or electron terminal output.

Any ideas on where to start with this? Im guessing some function is not firing when it is is rendered int he main window panels?

**Comment by jwu** [comment]
Hi @nibzo1 ,

The ui-tree is deprecated. This packages is out of date. I suggest you check the Vue's tree/list demo http://vuejs.org/examples/tree-view.html for it.

**Comment by jwu** [comment]
BTW: you can check this demo to learn how to work with Vue: https://github.com/exsdk/example-apps/tree/master/work-with-vue

**Comment by nibzo1** [comment]
great thanks for the update, I will investigate the use of tree/list  from the vuejs examples. Thanks
